smartdevicelink/sdl_android_guides

- docs/Getting Started/Upgrading to Multiplexing/index.md
- docs/Getting Started/index.md
> Added missing intent to SdlBR intent filter

- config.json
- docs/Advanced Topics/Calling A Phone Number/index.md
- docs/Advanced Topics/Setting the Navigation Destination/index.md
- docs/Advanced Topics/index.md
- docs/Basics/Alerts/index.md
- docs/Basics/Displaying Information/index.md
- docs/Basics/Uploading Graphics/index.md
- docs/Basics/index.md
Adding more topics to be covered.
> [WIP] Feature/overhaul

- docs/Getting Started/Upgrading to Multiplexing/index.md
- docs/Getting Started/index.md
> Fixing issues in Getting Started and Upgrading to Multiplexing Guides

- config.json
- docs/Handling Language Change/index.md
Corresponds with https://github.com/smartdevicelink/hello_sdl_android/pull/15 in hello_sdl
> Handling Language Change guide

- docs/Getting Started/Hello Sdl Android/index.md
- docs/Getting Started/index.md
Remove period
Remove unnecessary brackets
> Two simple issues

- docs/Displaying Information/Text Images and Buttons/index.md
> Adding docs on how to know if soft button was pressed

- config.json
- docs/Mobile Navigation/Introduction/index.md
- docs/Mobile Navigation/Video Streaming/index.md
> [WIP] Feature/video streaming

- config.json
- docs/Remote Control/index.md
Fixes #47  
Adding Guide(s) for Remote Control
> Feature / RC guides

- docs/Calling a Phone Number/index.md
- docs/Displaying Information/Alerts/index.md
- docs/Displaying Information/Designing the User Interface/index.md
- docs/Displaying Information/Menus/index.md
- docs/Displaying Information/Text Images and Buttons/index.md
- docs/Getting In-Car Audio/index.md
- docs/Getting Started/Compiling with Gradle/index.md
- docs/Getting Started/Hello Sdl Android/index.md
- docs/Getting Vehicle Data/index.md
- docs/Setting the Navigation Destination/index.md
- removed `setCorrelationID` from examples (except putFile)
- updated some language on hello sdl android page
> updating for 4.4

- docs/Mobile Navigation/Video Streaming/index.md
Fixes #58 
Class name and constructor now match.
> bugfix issue_58

- docs/Getting Started/index.md
Fixes #66 
added version so that developers do not have to look it up
> add compile line

- docs/Getting Started/Upgrading to Multiplexing/index.md
make sdl router service declaration match what we have in the getting started guide
> fix guide to match getting started

- docs/Getting Started/Upgrading to Multiplexing/index.md
- docs/Getting Started/index.md
- docs/Mobile Navigation/Video Streaming/index.md
Adding a few quick fixes to the guides. A few of these are urgent and not tied directly to a release of the android library, so a hotfix merge is the best choice.
> Hotfix release

- docs/System Capability Manager/index.md
update list of responses that are returned as lists
> update sys cap manager doc

- docs/Getting Started/index.md
Update GettingStarted to include foreground requirements.
Also made a few edits including proper code tagging and moving the Implementing IProxyListenerALM Methods section to the proper area.
> Update GettingStarted to include foreground requirements

- config.json
- docs/Mobile Navigation/Audio Streaming/index.md
- docs/Mobile Navigation/Video Streaming/index.md
Add in example code for streaming audio during navigation
> Navigation Audio Streaming Guide

- docs/Setting Security Level for Multiplexing/index.md
Changed the email address that didn't exist to the correct one.
> Fix incorrect email address

- docs/Setting Security Level for Multiplexing/index.md
> Update "Applying to the Trusted Router Service List"

- docs/Getting Started/Installation/index.md
> 4.7 installation updates

- config.json
- docs/Getting Started/Integration Basics/index.md
- docs/Migrating to Newer SDL Android Versions/Updating to 4.7/index.md
major re-write of integration basics and start of the upgrade guide
> 4.7 integration basics updates

- config.json
- docs/Getting Started/Sending Multiple RPCs/index.md
- docs/Migrating to Newer SDL Android Versions/Updating to 4.7/index.md
update send multiple rpc section in getting started
> 4.7 send multiple rpcs update

- config.json
- docs/Migrating to Newer SDL Android Versions/Updating to 4.7/index.md
- docs/Uploading Files and Graphics/index.md
re-write most of the uploading files and graphics guide to show the use of the `FileManager`
> 4.7 uploading files graphics update

- docs/Displaying Information/Text Images and Buttons/index.md
Add static images sample to screen manager docs
> Add static images docs

- docs/Getting Started/Integration Basics/index.md
Add block old head units guides
> Add block old head units

- config.json
- docs/App Services/Creating an App Service/index.md
- docs/App Services/Using App Services/index.md
add app services guides to match iOS
> App Services

- docs/Creating a Cloud App Store/index.md
- docs/System Capability Manager/index.md
- Add `APP_SERVICES` cap
- Update cloud app store page
> Some 4.8 additions  

- docs/Getting Started/Installation/index.md
> Update version to 4.8
